export const CITIES_BY_COUNTRY: Record<string, string[]> = {
  "Afghanistan": ["Kabul", "Kandahar", "Herat", "Mazar-i-Sharif", "Jalalabad"],
  "Albania": ["Tirana", "Durrës", "Vlorë", "Shkodër", "Fier"],
  "Algeria": ["Algiers", "Oran", "Constantine", "Annaba", "Blida", "Batna", "Tlemcen"],
  "Argentina": ["Buenos Aires", "Córdoba", "Rosario", "Mendoza", "Tucumán", "La Plata"],
  "Armenia": ["Yerevan", "Gyumri", "Vanadzor", "Vagharshapat"],
  "Australia": ["Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide", "Canberra", "Hobart"],
  "Austria": ["Vienna", "Graz", "Linz", "Salzburg", "Innsbruck", "Klagenfurt"],
  "Azerbaijan": ["Baku", "Ganja", "Sumqayit", "Mingachevir", "Nakhchivan"],
  "Bahrain": ["Manama", "Riffa", "Muharraq", "Hamad Town", "A'ali"],
  "Bangladesh": ["Dhaka", "Chittagong", "Khulna", "Rajshahi", "Sylhet", "Comilla"],
  "Belarus": ["Minsk", "Gomel", "Mogilev", "Vitebsk", "Grodno", "Brest"],
  "Belgium": ["Brussels", "Antwerp", "Ghent", "Charleroi", "Liège", "Bruges"],
  "Bolivia": ["Sucre", "La Paz", "Santa Cruz", "Cochabamba", "Oruro", "Potosí"],
  "Bosnia and Herzegovina": ["Sarajevo", "Banja Luka", "Tuzla", "Zenica", "Mostar"],
  "Brazil": ["São Paulo", "Rio de Janeiro", "Brasília", "Salvador", "Fortaleza", "Belo Horizonte", "Manaus", "Curitiba"],
  "Bulgaria": ["Sofia", "Plovdiv", "Varna", "Burgas", "Ruse", "Stara Zagora"],
  "Cambodia": ["Phnom Penh", "Siem Reap", "Battambang", "Sihanoukville"],
  "Canada": ["Toronto", "Montreal", "Vancouver", "Calgary", "Edmonton", "Ottawa", "Winnipeg", "Quebec City"],
  "Chile": ["Santiago", "Valparaíso", "Concepción", "La Serena", "Antofagasta"],
  "China": ["Beijing", "Shanghai", "Guangzhou", "Shenzhen", "Chengdu", "Wuhan", "Xi'an", "Hangzhou", "Chongqing", "Nanjing", "Tianjin"],
  "Colombia": ["Bogotá", "Medellín", "Cali", "Barranquilla", "Cartagena", "Bucaramanga"],
  "Croatia": ["Zagreb", "Split", "Rijeka", "Osijek", "Zadar", "Dubrovnik"],
  "Cuba": ["Havana", "Santiago de Cuba", "Holguín", "Guantánamo", "Santa Clara"],
  "Cyprus": ["Nicosia", "Limassol", "Larnaca", "Famagusta", "Paphos"],
  "Czech Republic": ["Prague", "Brno", "Ostrava", "Plzen", "Liberec", "Olomouc"],
  "Denmark": ["Copenhagen", "Aarhus", "Odense", "Aalborg", "Esbjerg"],
  "Dominican Republic": ["Santo Domingo", "Santiago", "La Romana", "San Pedro de Macorís"],
  "Ecuador": ["Quito", "Guayaquil", "Cuenca", "Ambato", "Manta"],
  "Egypt": ["Cairo", "Alexandria", "Giza", "Shubra El Kheima", "Port Said", "Suez", "Luxor", "Aswan", "Mansoura"],
  "El Salvador": ["San Salvador", "Soyapango", "San Miguel", "Santa Ana"],
  "Ethiopia": ["Addis Ababa", "Dire Dawa", "Gondar", "Mekele", "Hawassa"],
  "Finland": ["Helsinki", "Espoo", "Tampere", "Vantaa", "Oulu", "Turku"],
  "France": ["Paris", "Marseille", "Lyon", "Toulouse", "Nice", "Nantes", "Strasbourg", "Montpellier", "Bordeaux", "Lille"],
  "Georgia": ["Tbilisi", "Kutaisi", "Batumi", "Rustavi", "Zugdidi"],
  "Germany": ["Berlin", "Hamburg", "Munich", "Cologne", "Frankfurt", "Stuttgart", "Düsseldorf", "Leipzig", "Dortmund", "Dresden", "Nuremberg"],
  "Ghana": ["Accra", "Kumasi", "Tamale", "Sekondi-Takoradi", "Cape Coast"],
  "Greece": ["Athens", "Thessaloniki", "Patras", "Heraklion", "Piraeus", "Larissa"],
  "Guatemala": ["Guatemala City", "Quetzaltenango", "Mixco", "Villa Nueva"],
  "Hungary": ["Budapest", "Debrecen", "Miskolc", "Szeged", "Pécs", "Győr"],
  "India": ["Mumbai", "Delhi", "Bangalore", "Hyderabad", "Chennai", "Kolkata", "Pune", "Ahmedabad", "Jaipur", "Surat", "Lucknow", "Kanpur"],
  "Indonesia": ["Jakarta", "Surabaya", "Bandung", "Medan", "Bekasi", "Makassar", "Semarang", "Depok"],
  "Iran": ["Tehran", "Mashhad", "Isfahan", "Karaj", "Tabriz", "Shiraz", "Ahvaz", "Qom"],
  "Iraq": ["Baghdad", "Basra", "Mosul", "Erbil", "Najaf", "Karbala", "Kirkuk"],
  "Ireland": ["Dublin", "Cork", "Limerick", "Galway", "Waterford"],
  "Israel": ["Jerusalem", "Tel Aviv", "Haifa", "Rishon LeZion", "Petah Tikva", "Beer Sheva"],
  "Italy": ["Rome", "Milan", "Naples", "Turin", "Palermo", "Genoa", "Bologna", "Florence", "Bari", "Venice"],
  "Ivory Coast": ["Abidjan", "Bouaké", "Daloa", "San-Pédro", "Yamoussoukro"],
  "Japan": ["Tokyo", "Yokohama", "Osaka", "Nagoya", "Sapporo", "Fukuoka", "Kyoto", "Kobe", "Hiroshima", "Sendai"],
  "Jordan": ["Amman", "Zarqa", "Irbid", "Aqaba", "Madaba", "Karak"],
  "Kazakhstan": ["Almaty", "Nur-Sultan", "Shymkent", "Karaganda", "Aktobe", "Taraz"],
  "Kenya": ["Nairobi", "Mombasa", "Kisumu", "Nakuru", "Eldoret"],
  "Kuwait": ["Kuwait City", "Al Ahmadi", "Hawalli", "As Salimiyah", "Sabah as Salim"],
  "Kyrgyzstan": ["Bishkek", "Osh", "Jalal-Abad", "Karakol", "Tokmok"],
  "Lebanon": ["Beirut", "Tripoli", "Sidon", "Tyre", "Jounieh", "Baalbek"],
  "Libya": ["Tripoli", "Benghazi", "Misrata", "Bayda", "Sabha"],
  "Malaysia": ["Kuala Lumpur", "George Town", "Johor Bahru", "Ipoh", "Shah Alam", "Petaling Jaya"],
  "Mexico": ["Mexico City", "Guadalajara", "Monterrey", "Puebla", "Tijuana", "León", "Ciudad Juárez", "Mérida"],
  "Moldova": ["Chișinău", "Tiraspol", "Bălți", "Bender"],
  "Mongolia": ["Ulaanbaatar", "Erdenet", "Darkhan", "Choibalsan"],
  "Morocco": ["Casablanca", "Rabat", "Fez", "Marrakech", "Agadir", "Tangier", "Meknes", "Oujda"],
  "Myanmar": ["Yangon", "Mandalay", "Naypyidaw", "Mawlamyine", "Bago"],
  "Netherlands": ["Amsterdam", "Rotterdam", "The Hague", "Utrecht", "Eindhoven", "Groningen"],
  "New Zealand": ["Auckland", "Wellington", "Christchurch", "Hamilton", "Tauranga"],
  "Nigeria": ["Lagos", "Kano", "Ibadan", "Abuja", "Port Harcourt", "Benin City", "Maiduguri"],
  "North Macedonia": ["Skopje", "Bitola", "Kumanovo", "Tetovo", "Ohrid"],
  "Norway": ["Oslo", "Bergen", "Trondheim", "Stavanger", "Drammen"],
  "Oman": ["Muscat", "Seeb", "Salalah", "Bawshar", "Sohar", "Nizwa"],
  "Pakistan": ["Karachi", "Lahore", "Faisalabad", "Rawalpindi", "Gujranwala", "Islamabad", "Peshawar", "Multan", "Hyderabad"],
  "Palestine": ["Gaza", "Hebron", "Nablus", "Ramallah", "Jenin", "Tulkarm"],
  "Peru": ["Lima", "Arequipa", "Callao", "Trujillo", "Chiclayo", "Iquitos"],
  "Philippines": ["Manila", "Davao", "Cebu", "Quezon City", "Zamboanga", "Taguig"],
  "Poland": ["Warsaw", "Kraków", "Łódź", "Wrocław", "Poznań", "Gdańsk", "Szczecin"],
  "Portugal": ["Lisbon", "Porto", "Vila Nova de Gaia", "Amadora", "Braga", "Coimbra"],
  "Qatar": ["Doha", "Al Rayyan", "Umm Salal", "Al Wakrah", "Al Khor"],
  "Romania": ["Bucharest", "Cluj-Napoca", "Timișoara", "Iași", "Constanța", "Craiova", "Brașov"],
  "Russia": ["Moscow", "Saint Petersburg", "Novosibirsk", "Yekaterinburg", "Kazan", "Chelyabinsk", "Samara", "Ufa", "Rostov-on-Don", "Krasnodar"],
  "Saudi Arabia": ["Riyadh", "Jeddah", "Mecca", "Medina", "Dammam", "Khobar", "Tabuk", "Abha"],
  "Senegal": ["Dakar", "Touba", "Thiès", "Rufisque", "Kaolack"],
  "Serbia": ["Belgrade", "Novi Sad", "Niš", "Kragujevac", "Subotica"],
  "Singapore": ["Singapore"],
  "Slovakia": ["Bratislava", "Košice", "Prešov", "Žilina", "Nitra"],
  "Somalia": ["Mogadishu", "Hargeisa", "Kismayo", "Bosaso", "Marka"],
  "South Africa": ["Cape Town", "Johannesburg", "Durban", "Pretoria", "Port Elizabeth", "Bloemfontein"],
  "South Korea": ["Seoul", "Busan", "Incheon", "Daegu", "Daejeon", "Gwangju", "Suwon"],
  "Spain": ["Madrid", "Barcelona", "Valencia", "Seville", "Bilbao", "Málaga", "Murcia", "Palma", "Las Palmas", "Zaragoza"],
  "Sri Lanka": ["Colombo", "Dehiwala-Mount Lavinia", "Moratuwa", "Kandy", "Negombo", "Galle"],
  "Sudan": ["Khartoum", "Omdurman", "Port Sudan", "Kassala", "El Obeid"],
  "Sweden": ["Stockholm", "Gothenburg", "Malmö", "Uppsala", "Västerås", "Örebro"],
  "Switzerland": ["Zurich", "Geneva", "Basel", "Lausanne", "Bern", "Winterthur"],
  "Syria": ["Damascus", "Aleppo", "Homs", "Latakia", "Hama", "Deir ez-Zor"],
  "Tajikistan": ["Dushanbe", "Khujand", "Kulob", "Bokhtar", "Istaravshan"],
  "Tanzania": ["Dar es Salaam", "Mwanza", "Arusha", "Dodoma", "Zanzibar City"],
  "Thailand": ["Bangkok", "Chiang Mai", "Nonthaburi", "Pattaya", "Hat Yai", "Khon Kaen"],
  "Tunisia": ["Tunis", "Sfax", "Sousse", "Kairouan", "Bizerte", "Gabès"],
  "Turkey": ["Istanbul", "Ankara", "Izmir", "Bursa", "Antalya", "Adana", "Gaziantep", "Konya", "Mersin", "Diyarbakır", "Kayseri", "Eskişehir", "Trabzon", "Samsun"],
  "Turkmenistan": ["Ashgabat", "Turkmenabat", "Mary", "Dashoguz"],
  "Uganda": ["Kampala", "Gulu", "Lira", "Mbarara", "Jinja"],
  "Ukraine": ["Kyiv", "Kharkiv", "Odesa", "Dnipro", "Donetsk", "Zaporizhzhia", "Lviv"],
  "United Arab Emirates": ["Dubai", "Abu Dhabi", "Sharjah", "Al Ain", "Ajman", "Ras Al Khaimah"],
  "United Kingdom": ["London", "Birmingham", "Leeds", "Glasgow", "Sheffield", "Manchester", "Edinburgh", "Liverpool", "Bristol", "Cardiff"],
  "United States": ["New York", "Los Angeles", "Chicago", "Houston", "Phoenix", "Philadelphia", "San Antonio", "San Diego", "Dallas", "San Jose", "Austin", "Jacksonville", "Seattle", "Boston", "Denver"],
  "Uzbekistan": ["Tashkent", "Namangan", "Samarkand", "Andijan", "Nukus", "Bukhara", "Fergana"],
  "Venezuela": ["Caracas", "Maracaibo", "Valencia", "Barquisimeto", "Maracay"],
  "Vietnam": ["Ho Chi Minh City", "Hanoi", "Hai Phong", "Da Nang", "Bien Hoa", "Can Tho"],
  "Yemen": ["Sanaa", "Aden", "Taiz", "Hodeidah", "Mukalla"],
  "Zimbabwe": ["Harare", "Bulawayo", "Chitungwiza", "Mutare", "Gweru"],
};
